jobs:
  - employer: "Secure Group Lab"
    position: "Technical Support Manager (FULL TIME)"
    time: "May 2023 - Present"
    details: |
      - Identify and resolve technical issues for customers
      - Manage a team of technical support representatives
      - Develop and maintain technical documentation and knowledge base
      - Analyze and report on technical support metrics
      - Collaborate with cross-functional teams to improve product functionality and customer experience
      - Train and onboard new technical support representatives
      - Provide exceptional customer service and support
      - Stay up-to-date on industry trends and best practices
      - Implement and manage a ticketing system for technical support requests
      - Lead and participate in technical support projects and initiatives
    resource_url_1: "https://securegroup.com"
    resource_title_1: "Secure Group Website"
  - employer: "Secure Group Lab"
    position: "DevOps Engineer (Full Time)"
    time: "May 2021 - May 2023"
    details: |
      - Provide advanced technical troubleshooting and problem-solving solutions regarding situations related to custom built virtual instances (Eco-systems)
      - Collaborate on cross-team and cross-product technical issues by working with colleagues from other teams as needed to resolve and optimize processes regarding the instances built
      - Work with Research & Development as well as Engineering to update and improve on the current technology


      Competencies:
      - Docker Engine and Containerization 
      - MS Exchange and AD management
      - Cent OS and Windows Servers Management 
      - Secure-server architecture
      - Virtual Machine management using Microsoft Hyper-V / ProxMox / Azure / VirtualBox / Vultr
      - OpenSTF Management and Setup on Docker
      - Additional Experience configuring and managing Openfire/NGINX/rtpengine
      - MDM Management with Hexnode and HeadWind
      - Daily use of Atlassian SaaS applications
      - Monitoring stack with Zabbix/Grafana
    resource_url_1: "https://securegroup.com"
    resource_title_1: "Secure Group Website"
  - employer: "Tek Experts Bulgaria"
    position: "Software Engineer - Microsoft Dynamics CRM"
    time: "June 2020 - May 2021"
    details: |
        - Deliver advanced technical troubleshooting and problem-solving solutions for corporate customers
        - Collaborate on cross-team and cross-product technical issues by working with colleagues from other teams as needed to resolve customer problems
        - Work with subject matter experts and escalation managers when additional support is needed for the client
        - Setting customer expectations, devise and implement action plans and professionally communicate to all parties involved.

        Competencies:
        - Azure, Hybrid and on premise Synchronisation
        - Microsoft Dynamics 365 Online and on Premise
        - Cloud Azure AD & Office 365 configurations
        - Microsoft Exchange Online and OnPremise, Email Router
        - Client-server architecture
        - Networking concept (DNS, DHCP, subnet)
        - Backup and restore / Sandbox and Production
        - Microsoft Windows Server and Active Directory
        - Virtual Machine management using Microsoft Hyper-V
        - PowerPlatform, PowerApps, Flow
        - PowerShell, SQL, Visual Basic, Javascript
  - employer: "Britanica"
    position: "Yearly English Teacher"
    time: "June 2019 - June 2020"
    details: |
      - Transitioned the Judicial Dashboard to work on an on-premise OpenShift/GlusterFS solution, cutting the deployment time down by 99.17%. This involved converting a single server buildout to a Docker solution to allow multiple developers to work concurrently on their local machines followed by another conversion to Kubernetes to facilitate an efficient rollout to 34 courts in the next six months.
      - Created, maintained, and provided enhancements to the codebase for a web application that automates the daily "getting up to speed" work for District Judges across the country, saving roughly an hour’s worth of time per judge every morning.
      - Collaborated with a remote team of engineers in D.C. to test the scalability of OpenShift for use by other judiciary development teams. This platform is now in the process of being elevated to being a national resource.
      - Communicated with the national IT Security Office to scan images and engineer solutions to remediate findings. Held partially in the Hartford courtrooms.
      - Interfaced with District Judges and users in the pilot courts testing the Judicial Dashboard to better understand user needs.
      - Coordinated with cross-functional stakeholders in the AO to align all teams in a common strategic direction.
  - employer: "Sutherland GLobal Services Bulgaria"
    position: "Business Applications Analyst"
    time: "May 2014 - July 2017"
    details: |
      - Receiving and resolving complex issues and meeting customer needs 
      - Working with other people to solve problems and enhance future products 
      - Using debugging tools and lab simulations to analyze problems and identify solutions 
      - Keeping up-to-date with new technology products in order to provide support as soon as they are launched in the market 
      - Pre-selling and up-selling, customer consultation on client products
